# Generated by Django 2.0.4 on 2018-04-17 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180417_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='aritcle_image',
            new_name='article_image',
        ),
    ]
